name: "xxPROJECTxNAMExx CI"

on: 
  push:
    branches: 
      - main
    paths:
      - 'Sources/**'
      - 'Tests/**'
      - '.github/workflows/**'
      - 'Package.swift'
      - 'Example/**'
  pull_request:
    paths:
      - 'Sources/**'
      - 'Tests/**'
      - '.github/workflows/**'
      - 'Package.swift'
      - 'Example/**'
  workflow_call:

concurrency: 
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  swift-package:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runsOn }}
    env:
      DEVELOPER_DIR: "/Applications/${{ matrix.xcode }}.app/Contents/Developer"
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - xcode: "Xcode_16.3"
            runsOn: macos-latest
            name: "macOS, Xcode 16.3, Swift 6.1"
          - xcode: "Xcode_15.4"
            runsOn: macos-14
            name: "macOS 14, Xcode 15.4, Swift 5.10"
          - xcode: "Xcode_15.2"
            runsOn: macos-13
            name: "macOS 13, Xcode 15.2, Swift 5.9.2"
    steps:
      - uses: actions/checkout@v4
      - name: Swift Package Test
        run: |
          set -o pipefail
          swift build
          swift test

  example-app:
    name: Example App - ${{ matrix.name }}
    runs-on: ${{ matrix.runsOn }}
    env:
      DEVELOPER_DIR: "/Applications/${{ matrix.xcode }}.app/Contents/Developer"
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - xcode: "Xcode_16.3"
            runsOn: macos-latest
            name: "iOS Simulator"
            destination: "platform=iOS Simulator,name=iPhone 15 Pro"
          - xcode: "Xcode_15.4"
            runsOn: macos-14
            name: "iOS Simulator"
            destination: "platform=iOS Simulator,name=iPhone 15 Pro"
    steps:
      - uses: actions/checkout@v4
      - name: Build Example App
        run: |
          set -o pipefail
          cd Example
          xcodebuild -project Example.xcodeproj -scheme Example -destination "${{ matrix.destination }}" clean build

