name: Swiftlang workflows

# Adapted from https://github.com/apple/swift-collections/blob/bdfaffbba691f037100b115d9aa801f05e3d7fe8/.github/workflows/pull_request.yml

on:
  push:
  pull_request:

jobs:
  tests:
    name: Test
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@main
    with:
      linux_exclude_swift_versions: '[{"swift_version": "5.8"}, {"swift_version": "5.9"}, {"swift_version": "5.10"}, {"swift_version": "6.0"}, {"swift_version": "6.1"}]'
      windows_exclude_swift_versions: '[{"swift_version": "5.9"}, {"swift_version": "5.10"}]'
      macos_exclude_xcode_versions: '[{"xcode_version": "26.0"}]'
      enable_macos_checks: true
      enable_wasm_sdk_build: true

  embedded-swift:
    name: Build with Embedded Swift
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@main
    with:
      enable_linux_checks: false
      enable_macos_checks: false
      enable_windows_checks: false
      enable_wasm_sdk_build: false
      enable_embedded_wasm_sdk_build: true
      swift_flags: --target "xxPROJECTxNAMExx"

  soundness:
    name: Soundness
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@main
    with:
      license_header_check_project_name: "xxPROJECTxNAMExx"
